# MIT License
#
# Copyright (c) 2023 Ivan Specht
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#' Plot Current Network Configuration
#'
#' This function plots the current network topology as the Markov chain runs.
#'
#' @param init State of the Markov chain, in the same format as generated by initialize().
#' @param type Either "standard" (default), which returns a standard phylogenetic tree layout, or "radial", which returns a radial tree layout.
#' @return The network plot.
#' @export
plot_network <- function(init, type = "standard"){
  mcmc <- init[[1]]
  data <- init[[2]]
  if(type == "standard"){
    # Phylo plot

    h <- mcmc$h
    t <- sapply(mcmc$seq, function(v){v[1]})
    n <- length(h)
    ord <- rev(dfs(h))

    leaves <- which(!(1:mcmc$n %in% mcmc$h))
    n_leaves <- length(leaves)

    # Angle of each node
    thetas <- c()
    leaf_count <- 0

    for (i in ord) {
      if(!(i %in% leaves)){
        kids <- which(h == i)
        thetas[i] <- mean(thetas[kids])
      }else{
        thetas[i] <- leaf_count * 2 * pi / n_leaves
        leaf_count <- leaf_count + 1
      }
    }

    df_standard <- data.frame(x =t, y = thetas)


    # vertical segments
    xs <- c()
    ystart <- c()
    yend <- c()

    who <- 1:mcmc$n

    for (i in who) {
      kids <- which(h == i)
      if(length(kids) > 0){
        xs <- c(xs, t[i])
        ystart <- c(ystart, min(thetas[kids]))
        yend <- c(yend, max(thetas[kids]))
      }
    }

    colors <- rep('black', length(who))
    colors[who > data$n_obs] <- 'gray'

    if(!data$rooted){
      colors[1] <- 'gray'
    }

    t <- data$s_max + t
    xs <- data$s_max + xs
    df_standard$x <- data$s_max + df_standard$x


    big <- ggplot2::ggplot() +
      ggplot2::geom_segment(mapping = ggplot2::aes(x = (t[h])[-1], xend = t[-1], y = thetas[-1], yend = thetas[-1]), linewidth = 0.5) +
      ggplot2::geom_segment(mapping = ggplot2::aes(x = xs, xend = xs, y = ystart, yend = yend), linewidth = 0.5) +
      ggplot2::geom_point(mapping = ggplot2::aes(x = df_standard$x, y = df_standard$y, color = colors), size = 1) +
      ggplot2::xlab("Date") +
      ggplot2::scale_y_continuous(breaks = NULL) +
      ggplot2::scale_color_manual(values = c("black", "gray")) +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        axis.title.y = ggplot2::element_blank(),
        legend.position='none'
      )
    big

  }else if(type == "radial"){
    h <- mcmc$h
    n_obs <- data$n_obs
    n <- length(h)
    vertices <- data.frame(name = 1:n)
    edges <- as.data.frame(cbind(paste(h[2:n]), paste(2:n)))
    colnames(edges) <- c('from', 'to')
    g <- igraph::graph_from_data_frame(edges)
    colors <- rep('black', n)
    colors[1:n > n_obs] <- 'gray'
    p <- ggraph::ggraph(edges, layout = 'dendrogram', circular = T) +
      ggraph::geom_edge_elbow() +
      ggraph::geom_node_point(ggplot2::aes(color = as.numeric(name) > n_obs), size = 5) +
      ggraph::geom_node_text(ggplot2::aes(label=name), size=2.5, color = 'white') +
      ggplot2::scale_color_manual(values = c("black", "gray")) +
      ggraph::theme_graph() +
      ggplot2::coord_fixed() +
      ggplot2::theme(legend.position = 'none')
    p
  }
}
