# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_sum_exp <- function(u, v) {
    .Call(`_juniper0_log_sum_exp`, u, v)
}

log_subtract_exp <- function(u, v) {
    .Call(`_juniper0_log_subtract_exp`, u, v)
}

log_sum_exp_vec <- function(w) {
    .Call(`_juniper0_log_sum_exp_vec`, w)
}

wbar <- function(tinf, dateT, rOff, pOff, pi, shGen, scGen, shSam, scSam, delta_t) {
    .Call(`_juniper0_wbar`, tinf, dateT, rOff, pOff, pi, shGen, scGen, shSam, scSam, delta_t)
}

probTTree <- function(ttree, rOff, pOff, pi, shGen, scGen, shSam, scSam, dateT, wbar0, delta_t = 0.01) {
    .Call(`_juniper0_probTTree`, ttree, rOff, pOff, pi, shGen, scGen, shSam, scSam, dateT, wbar0, delta_t)
}

dprop <- function(x, mu, LOG) {
    .Call(`_juniper0_dprop`, x, mu, LOG)
}

dprop_bounded <- function(x, N, mu, LOG) {
    .Call(`_juniper0_dprop_bounded`, x, N, mu, LOG)
}

ppropBoundedHelper <- function(x, N, mu) {
    .Call(`_juniper0_ppropBoundedHelper`, x, N, mu)
}

pprop_bounded <- function(x, N, mu) {
    .Call(`_juniper0_pprop_bounded`, x, N, mu)
}

pprop <- function(x, mu, LOG) {
    .Call(`_juniper0_pprop`, x, mu, LOG)
}

sprop <- function(x, mu, LOG) {
    .Call(`_juniper0_sprop`, x, mu, LOG)
}

